### ISSUE TITLE
Portuguese missing (& other languages)

### ISSUE THREAD

**Issue by seanmacavaney** [unicamp-dl/mMARCO#1]
Hi,

Thanks for providing this resource! I noticed that the Portuguese collections are missing: https://console.cloud.google.com/storage/browser/msmarco-translated/multi_msmarco/portuguese;tab=objects?prefix=&forceOnObjectsSortingFiltering=false

Also, navigating a bit through the console, I saw a few other languages as well that were not covered in the paper or linked in the repo (Arabic, Hindi, and Japanese). Are these all set to use as well, i.e., have they been validated?

Thanks!

**Comment by lhbonifacio** [comment]
Hi @seanmacavaney 

Thanks for informing us about the missing of Portuguese collection translation.
The files were already add to the bucket.

About the languages available in the bucket but not covered in the paper, we noticed some problems when working with these three collections (both in initial retrieval and re-ranking). We are still trying to figure out what (or where) are the problems. Feel free to test it and reporting us the results ;)

**Comment by seanmacavaney** [comment]
awesomesauce, thanks!
