### ISSUE TITLE
Loading mMARCO using HuggingFace Datasets API

### ISSUE THREAD

**Issue by atamborrino** [unicamp-dl/mMARCO#13]
Hello,

First, thanks for the great work and making the dataset available!

I'm having issues loading this dataset using the HuggingFace `datasets` API, following your [README example](https://huggingface.co/datasets/unicamp-dl/mmarco):
```
dataset = load_dataset('unicamp-dl/mmarco', language='portuguese')
```

It produces the following error:
```
TypeError: __init__() got an unexpected keyword argument 'language'
```

When removing the `language` parameter, the dataset downloaded but then the reading failed with the following error:
```
Failed to read file '/home/jupyter/.cache/huggingface/datasets/downloads/a9967334116edef6ec42dea5f2d25bb38b28b765aa427f59f6cd1a559d3f213d' with error <class 'pandas.errors.ParserError'>: Error tokenizing data. C error: Expected 1 fields in line 45, saw 2
```

Any ideas of the issue? Thanks!

**Comment by hugoabonizio** [comment]
Hi @atamborrino, we updated the loading script to make it easier to access. Now you can load the training triples with:

```python
>>> dataset = load_dataset('unicamp-dl/mmarco', 'portuguese')
DatasetDict({
    train: Dataset({
        features: ['query', 'positive', 'negative'],
        num_rows: 39780811
    })
})
```

You can also load the translated collections or queries by using the `collection-` and `queries-` prefixes:

```python
>>> load_dataset('unicamp-dl/mmarco', 'collection-english')
DatasetDict({
    collection: Dataset({
        features: ['id', 'text'],
        num_rows: 8841823
    })
})

>>> load_dataset('unicamp-dl/mmarco', 'queries-spanish')
DatasetDict({
    train: Dataset({
        features: ['id', 'text'],
        num_rows: 808731
    })
    validation: Dataset({
        features: ['id', 'text'],
        num_rows: 101093
    })
})
```

The list of supported languages and their codes is available [here](https://huggingface.co/datasets/unicamp-dl/mmarco).

**Comment by atamborrino** [comment]
Thanks, it's working! 👍
