### ISSUE TITLE
problem in japanese data

### ISSUE THREAD

**Issue by guijuzhejiang** [unicamp-dl/mMARCO#17]
{"query":"ロイヤルガードは誰ですか","positive":"Talk78共有。ロイヤルガード（ÃƒÂ§Ã‚Å½Ã‚â€¹ÃƒÂ¥Ã‚Â±Ã‚Å¾ÃƒÂ§Ã‚â€°Ã‚Â¹ÃƒÂ¥Ã‚â€¹Ã‚â„¢、Ãƒâ€¦Ã‚Å'zokutokumu;ゼロディビジョン（ÃƒÂ©Ã‚â€ºÃ‚Â¶ÃƒÂ§Ã‚â€¢Ã‚ÂªÃƒÂ©Ã‚Å）としても知られている英語のダブでロイヤルスペシャルタスクフォースとして翻訳され、文字通りキング従属秘密サービスとして翻訳された¡Ã‚Å、Zerobantai）は、ソウルキング、ロイヤルファミリー、ソウルキングパレスの保護に取り組んでいる組織です。","negative":"ローヤルゼリーの背の高い壺。働きバチの分泌物であるローヤルゼリーは、コロニー内のすべての幼虫に与えられるのと同じ物質です。ミツバチのコロニーが新しい女王蜂を必要とするとき、幼虫の小さなグループに大量のローヤルゼリーが与えられ、その摂食の変化はそれらの幼虫の女王蜂への成長を促します。"}

why 'ÃƒÂ§Ã‚Å½Ã‚â€¹ÃƒÂ¥Ã‚Â' show in some data, how can i filter them

**Comment by lhbonifacio** [comment]
Hey @guijuzhejiang 
Thank you for using mMARCO.
Regarding the problem in Japanese data, there are some codification issues in the original English version for some passages in the MS MARCO dataset. To overcome this, we use the [ftfy](https://ftfy.readthedocs.io/en/latest/), to take in bad Unicode and output good Unicode. Unfortunately, sometimes the codification issue is not completely solved and the translated text may present some unwanted characters. 
As the example you are mentioning, we have the English text:

> Share Talk78. Royal Guard (ÃƒÂ§Ã‚Å½Ã‚â€¹ÃƒÂ¥Ã‚Â±Ã‚Å¾ÃƒÂ§Ã‚â€°Ã‚Â¹ÃƒÂ\Ã‚â€¹Ã‚â„¢, Ãƒâ€¦Ã‚Å'zokutokumu; zero Also known as The Division (ÃƒÂ©Ã‚â€ºÃ‚Â¶ÃƒÂ§Ã‚â€¢Ã‚ÂªÃƒÂ©Ã‚Å) in the English dub, translated as Royal Special Task Force, literally King Subordinate Secret Service ¡Ã‚Å, Zerobantai) is an organization dedicated to protecting the Soul King, the Royal Family and the Soul King Palace

With some unwanted characters as **Ã** and **Å**.

In cases similar to the example you are mentioning, you can try to apply the ```ftfy``` library to the translated text as follow:
```
import ftfy
ftfy.ftfy("Talk78共有。ロイヤルガード（ÃƒÂ§Ã‚Å½Ã‚â€¹ÃƒÂ¥Ã‚Â±Ã‚Å¾ÃƒÂ§Ã‚â€°Ã‚Â¹ÃƒÂ¥Ã‚â€¹Ã‚â„¢、Ãƒâ€¦Ã‚Å'zokutokumu;ゼロディビジョン（ÃƒÂ©Ã‚â€ºÃ‚Â¶ÃƒÂ§Ã‚â€¢Ã‚ÂªÃƒÂ©Ã‚Å）としても知られている英語のダブでロイヤルスペシャルタスクフォースとして翻訳され、文字通りキング従属秘密サービスとして翻訳された¡Ã‚Å、Zerobantai）は、ソウルキング、ロイヤルファミリー、ソウルキングパレスの保護に取り組んでいる組織です。")
```
The output should be like this:

> Talk78共有。ロイヤルガード(王属特務、Ã…ÂÅ'zokutokumu;ゼロディビジョン(零番éÂÅ)としても知られている英語のダブでロイヤルスペシャルタスクフォースとして翻訳され、文字通りキング従属秘密サービスとして翻訳された¡Ã'Å、Zerobantai)は、ソウルキング、ロイヤルファミリー、ソウルキングパレスの保護に取り組んでいる組織です。

We know it's not a perfect solution, but it's possible to remove most of the problematic characters.
