### ISSUE TITLE
What is the license of the dataset?

### ISSUE THREAD

**Issue by PhilipMay** [unicamp-dl/mMARCO#19]
The code and documentation is Apache 2.0.
But which license is the dataset please?

**Comment by lhbonifacio** [comment]
Hey @PhilipMay 
Thanks for the interest in our work!

I just added this information to the [dataset card in the huggingface repo](https://huggingface.co/datasets/unicamp-dl/mmarco#licensing-information).
The dataset is also released under [Apache license 2.0](https://www.apache.org/licenses/).
