### ISSUE TITLE
How to reproduce the BM25 scores ?

### ISSUE THREAD

**Issue by LoicDagnas** [unicamp-dl/mMARCO#2]
Hi,

First of all, thanks a lot for sharing these datasets ! 

I don't want to pry, but I was wondering how did you get the BM25 scores for each language in the paper? Which values of `k1` and `b` did you use? 

Trying to reproduce your scores using pyserini, `k1=0.82` and `b=0.68` which are the parameters optimized for MSMARCO english passages, I reach scores terribly lower than yours ...

Thanks

**Comment by lhbonifacio** [comment]
Hi @LoicDagnas 
I am sorry by the delayed answer.
We added some information about the BM25 Indexing and Searching for mMARCO Portuguese collection.
The steps reported for this language are exactly the same used for all the other languages in mMARCO.
The values of `k1` and `b` were set as default (`--k1 0.82 --b 0.68`). We used `pyserini==0.10.0.1`.

Also, [we added a script for re-ranking](https://github.com/unicamp-dl/mMARCO/blob/main/scripts/reranker.py). 

Please, let us know if after this steps you still reaching lower scores.

**Comment by LoicDagnas** [comment]
@lhbonifacio thanks you for you answer. We have the exact same configuration in fact except the version of pyserini. We are going to dig a bit more with the example you provide for Portuguese, I'll keep you up to date here.
