### ISSUE TITLE
What are the hyper-parameters values used to train mT5-base models?

### ISSUE THREAD

**Issue by cramraj8** [unicamp-dl/mMARCO#21]
@rodrigonogueira4  Especially, `unicamp-dl/mt5-base-en-msmarco` model ?

**Comment by rodrigonogueira4** [comment]
Hi @vjeronymo2 you are probably the one who knows this answer, right?

**Comment by lhbonifacio** [comment]
Hey @cramraj8 

You can find this information in our paper, more specifically in the **3.3 Experimental Setup** section.
https://arxiv.org/abs/2108.13897

**Comment by cramraj8** [comment]
Hi @lhbonifacio , thanks for point out. I do want to know about the other details, such as batch size, number of negatives per positive pairs, what kind of hard negatives were used, and number of epochs. Did you already share the mT5 training script somewhere ? Are there any differences in training mT5-base and mT5XXL (13B) because I guess 13B might not be able to fit in traditional GPU?
