### ISSUE TITLE
Why .txt files (queries.dev, queries.train) present in Portuguese whereas .tsv for rest?

### ISSUE THREAD

**Issue by thakur-nandan** [unicamp-dl/mMARCO#3]
Hi, 

First of all, thank you for providing this resource. It's a great resource and with all the translations, I hope better multilingual retrievers will be attempted in the future. 

I wanted to ask why Portuguese (https://console.cloud.google.com/storage/browser/msmarco-translated/multi_msmarco/portuguese) has ``.txt`` files while the rest of the languages contain ``.tsv``. Was this just a casual mistake? Or were there issues when converting into a tsv file?

Kind Regards,
Nandan

**Comment by lhbonifacio** [comment]
HI @NThakur20,
Thanks for the observation. It was a casual mistake and it is already corrected.

**Comment by thakur-nandan** [comment]
Thank you :)
