### ISSUE TITLE
Question on reranking with multilingual-MiniLM

### ISSUE THREAD

**Issue by jobergum** [unicamp-dl/mMARCO#5]
Thanks for the excellent paper and publishing the translated MS Marco datasets and models. 

I notice that your reranker script uses pygaggle reranker MonoT5 which is the default model argument - what did you use for the MiniLM-L6?  I assume MonoBERT from pygaggle?

**Comment by lhbonifacio** [comment]
Hi @jobergum.
Thanks for your comments about our work. We hope it encourages other researchers to use our translated datasets.
About using MiniLM-L6 reranker, we used [SentenceTransformersReranker](https://github.com/castorini/pygaggle/blob/master/pygaggle/rerank/transformer.py#L298) from pygaggle.

**Comment by jobergum** [comment]
Thanks a lot for the quick feedback.
