### ISSUE TITLE
How to finetune the model on mMarco

### ISSUE THREAD

**Issue by shunyuzh** [unicamp-dl/mMARCO#9]
Hi folks,

Thanks for your awesome work. I wanna know how to fine-tune my own model on mMarco dataset? Would you like give some tutorial?

Thanks in advance.

**Comment by lhbonifacio** [comment]
Hello @Dopaminezsy.
Thanks for using our translated datasets.
So, until now, we have fine-tuned T5 and minilLM (both mono and multilingual) models on our translated data.
You can find some information on how to fine-tune T5 model [here](https://github.com/castorini/pygaggle/blob/master/docs/experiments-monot5-tpu.md#train-a-monot5-reranker) and miniLM model [here](https://www.sbert.net/docs/pretrained-models/ce-msmarco.html).
Also, we are about to update the mMARCO dataset with high quality translated data (and consequently better evaluation results). With this new version, we can provide a notebook with some examples on how to fine-tune and evaluate these models.

Thank you for your comments.

**Comment by shunyuzh** [comment]
Thanks. So your fine-tuned stage is totally the same as the given links, while the only difference is that the data is replaced with your translated datasets. Is that right?

**Comment by lhbonifacio** [comment]
@Dopaminezsy Yes, exactly.
